file_format: "1"
id: waterfoul
name: waterfoul
type: shield
url: https://github.com/foostan/crkbd/
requires:
  - nice_nano_v2
exposes:
  - i2c_oled
features:
  - keys
  - display
siblings:
  - waterfoul_left
  - waterfoul_right