file_format: "1"
id: waterfowl
name: Waterfowl
type: shield
url: https://waterfowl.bio.link/
requires: [pro_micro]
features:
  - keys
  - display
  - encoder
siblings:
  - waterfowl_left
  - waterfowl_right
